### ISSUE TITLE
Mssing a .h file

### ISSUE THREAD

**Issue by xcjian** [tansey/gfl#13]
I tried to install using pip and from source. Both give me the following same error. For example, when I runt the following command

`python 3.9 setup.py build `
I get

```
running build
running build_py
running build_ext
building 'libgraphfl' extension
gcc -pthread -B /usr/anaconda3/envs/xcnum_dl/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/anaconda3/envs/xcnum_dl/include -fPIC -O2 -isystem /usr/anaconda3/envs/xcnum_dl/include -fPIC -Icpp/include/ -I/usr/anaconda3/envs/xcnum_dl/include/python3.9 -c cpp/src/bayes_gfl.c -o build/temp.linux-x86_64-3.9/cpp/src/bayes_gfl.o
cpp/src/bayes_gfl.c:20:11: fatal error: bayes_gfl.h: No such file or directory
   20 |  #include "bayes_gfl.h"
      |           ^~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

I have no idea where the "bayes_gfl.h" is.

**Comment by tansey** [comment]
hi. it's been a while since looking at this project. i believe you need to compile the c code first and add ligraphfl to your path. bayes_gfl.h is here https://github.com/tansey/gfl/blob/master/cpp/include/bayes_gfl.h. so first build the shared library manually.

**Comment by xcjian** [comment]
> hi. it's been a while since looking at this project. i believe you need to compile the c code first and add ligraphfl to your path. bayes_gfl.h is here https://github.com/tansey/gfl/blob/master/cpp/include/bayes_gfl.h. so first build the shared library manually.

Thank you so much for your prompt reply! You have helped me solve this problem!
