### ISSUE TITLE
Is it possible to utilize weighted graph?

### ISSUE THREAD

**Issue by silent567** [tansey/gfl#6]
Hi, thank you for sharing the codes. It is very helpful.

I am wondering if it's possible to add weigths on edges, so that the loss function will be 
L(y,\beta)+\sum_{i<j}A_{ij}|\beta_i-\beta_j|

Can this project solve it with a few modifications?

**Comment by tansey** [comment]
Hi, unclear! I was never able to figure out whether Nick Johnson's 1D fused lasso solver (https://amstat.tandfonline.com/doi/abs/10.1080/10618600.2012.681238) could be extended to weighted fused lasso. If it can, then yes! If not, then probably not.

**Comment by silent567** [comment]
Thank you very much! So I need to find one weighted fused lasso solver to modify. It's restricted to extending Nick Johnson's solver, right?

**Comment by tansey** [comment]
If you can find any linear time weighted 1D fused lasso solver, you can incorporate it into the algorithm. It doesn't strictly have to be linear time, but the algorithm will be much slower if it's not.

**Comment by silent567** [comment]
Got it. I will firstly test the unweighted one to see if the performance is satisfying. Thank you very much!
