### ISSUE TITLE
python2 compatibility: "NetworkXError: Frozen graph can't be modified"

### ISSUE THREAD

**Issue by silent567** [tansey/gfl#8]
Got an error while running solve_gfl in easy.py using python2. 
Error code: "NetworkXError: Frozen graph can't be modified" (File "trail.py", line 391, in decompose_graph)

And I have found the graph producing the error:
Node number 36, 
edges:
```
0 6
0 8
0 9
1 7
1 10
1 11
2 4
2 5
3 4
3 5
3 6
3 7
8 12
8 14
9 13
9 15
10 16
11 17
12 13
12 18
13 19
14 20
15 21
16 24
16 26
17 25
17 27
18 22
19 23
20 22
21 23
24 28
25 29
26 30
27 31
28 32
28 34
29 33
29 35
30 32
31 33
```

codes to reproduce the error:
```
from pygfl.easy import solve_gfl
import numpy as np
a = np.random.rand(36)
edges = np.loadtxt('edges.txt')
solve_gfl(a,edges)
```

The errror only occurs in python2. No error is reported while utilizing python3, which is strange.

I am trying to make my project compatible with python3. But it's huge and managed by many co-workers. 

Could you help to fix this error? I am doubting that there is something different in networkx between python2 and python3.

Thank you very much!

**Comment by silent567** [comment]
I have done more experiments on different servers. It seems that same problem exists in python3.5, but not in python 3.6.

**Comment by tansey** [comment]
There are actually some breaking changes that networkx made when it released a new version a while ago. I can try to get around to this when I have time, but there are ML conference deadlines soon that are taking a lot of my time for the next few weeks. My suggestion would be to just create the trails yourself (this is a pretty trivial thing to do) and use the rest of the solver by passing it the trails explicitly.
